title: "Tiago Adorno"
description: "Assistant Professor of Physics | Theoretical High-Energy Physics"
theme: jekyll-theme-minimal

author: "Tiago Adorno"
email: "Tiago.Adorno@xjtlu.edu.cn"
show_downloads: false
